apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: edge01
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/12
  topology:
    class: kind
    controlPlane:
      metadata: {}
      replicas: 1
    variables:
    version: v1.27.2
    #workers:
    #  machineDeployments:
    #  - class: docker-default-worker
    #    name: md-0
    #    replicas: 1